project:
  type: website
  output-dir: docs
  
website:
  title: "websitetake3.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - Projects.qmd

format:
  html:
    theme: cosmo
    mainfont: times new roman
    css: styles.css
    toc: true
    toc-location: right

editor: visual

