---
title: "Resume"
author: "Carson Bainbridge"
About:
  template: broadside
---

**SUMMARY**

Majoring in ecosystem science and sustainability with an interest in the field of environmental education and climate research. While in school, I have been involved with the women’s club lacrosse team, Jewish life, mentored research program, as well as various outdoor recreation activities. I am most skilled in Microsoft Office suite, watershed science, ecology, sustainability, chemistry foundations, as well as time management and organization. I have worked as a chemistry tutor and an outdoor guide in the recreation program for students.  My core qualities of reliability, communication, and interpersonal skills have contributed to my ability to succeed as a student and employee. I seek to contribute with my wide range of knowledge, and drive to work hard to be successful in this position.

**EDUCATION**

### Outdoor Programs Instructor, CSU Campus Recreation                                     Aug 2024 – Present

Fort Collins, CO

-     Training in rock climbing skills, leadership skills, safety, guide principles, and how to plan and prepare for a trip.

-     Experience guiding (basic) rock climbing trips, backpacking, camping, and hiking trips in areas around Colorado.

-     Worked closely with coworkers to successfully lead people safely into the backcountry areas of Colorado.

### Chemisty Learning Assistant, TILT center\| Fort Collins, CO                                                        Aug-Dec 2024

-     Developed learning plans for small group learning sessions and facilitated learning in group sessions.

-     Developed great question asking skills to make students think, rather than give them the answers.

-     Built rapport with students to foster a safe and inclusive learning environment.

### **Tubing Hill Attendant, The Summit at Snoqualmie \|** Snoqualmie, WA

###                    Winter 2023, 2024

-     Facilitated guest interaction.

-     Ensured all guests followed safety protocols, while also working to actively prevent problems from happening.

-     Worked in adverse conditions, while performing manual labor.

### Lake Sammamish Concession Stand \| Lake Sammamish State Park, WA                                 May-August 2023,2024

-     Ability to work in a fast-paced environment

-     Proficiency in communication to work together with coworkers

-     Reliability to show up to work on time and in uniform

# Other Relevant Experience

FUNDRAISING AND MERCHANDISE OFFICER, CSU CLUB LACROSSE                              Aug 2024- Present

Fort Collins, CO

-     Managed club merchandise including creating, ordering, and facilitating distribution to members.

-     Communicated and organized fundraising events including volunteering for football and basketball games.

-     Worked amongst an officer team to ensure proper planning for the club to succeed. 

SKILLS FOR UNDERGRADUATE PARTICIPATION IN ECOLOGICAL RESEARCHAug 2024- present

Fort Collins, CO

-     Researched snowpack properties alongside a mentor.

-     Participated in research conferences (spring 2025).

-      Developed a full research report based on findings.

[***CERTIFICATIONS***]{.underline}

NOLS Wilderness First Responder certified \| January 2025

Red Cross CPR and first aid certified \| September 2024
